import { Trophy, Zap, Users, TrendingUp } from "lucide-react";

const packagesData = [
  {
    id: 1,
    name: "Genz Package",
    price: "1,500",
    originalPrice: "2,000",
    description:
      "The ultimate package for serious earners. Maximum daily view limits, priority access to all products, and exclusive featured listings.",
    benefits: [
      "View up to 8 products daily",
      "Priority access to all products",
      "Access to featured & exclusive offers",
      "Highest priority products (priority 0+)",
      "KSH 100 registration bonus",
      "24/7 premium support",
    ],
    gradient: "from-amber-400 via-yellow-500 to-amber-600",
    bgPattern: "from-amber-50 to-yellow-50",
    icon: <Zap className="w-7 h-7" />,
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
    popular: true,
    badge: "Most Popular",
    badgeColor: "bg-amber-500",
  },
  {
    id: 2,
    name: "Mbogi Package",
    price: "1,000",
    originalPrice: "1,400",
    description:
      "For the squad that hustles smart. Solid daily earning opportunities with priority access and featured listings.",
    benefits: [
      "View up to 6 products daily",
      "Priority access to products",
      "Access to featured listings",
      "Priority 1+ products access",
      "KSH 100 registration bonus",
      "Email support included",
    ],
    gradient: "from-slate-500 via-gray-600 to-slate-700",
    bgPattern: "from-gray-50 to-slate-50",
    icon: <Users className="w-7 h-7" />,
    iconBg: "bg-gray-100",
    iconColor: "text-gray-600",
    popular: false,
    badge: "Great Value",
    badgeColor: "bg-gray-500",
  },
  {
    id: 3,
    name: "Baller Package",
    price: "750",
    originalPrice: "1,000",
    description:
      "Step up your earnings game. Priority access to products with decent daily view limits for consistent income.",
    benefits: [
      "View up to 4 products daily",
      "Priority access to products",
      "Priority 2+ products access",
      "KSH 100 registration bonus",
      "Upgrade anytime",
      "Standard support",
    ],
    gradient: "from-orange-500 via-red-500 to-pink-600",
    bgPattern: "from-orange-50 to-red-50",
    icon: <TrendingUp className="w-7 h-7" />,
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    popular: false,
    badge: "Recommended",
    badgeColor: "bg-orange-500",
  },
  {
    id: 4,
    name: "Comrade Package",
    price: "500",
    originalPrice: "700",
    description:
      "Your entry point to consistent earnings. Reliable daily views with access to standard products for beginners.",
    benefits: [
      "View up to 3 products daily",
      "Priority 3+ products access",
      "KSH 100 registration bonus",
      "Perfect starter package",
      "Upgrade anytime",
      "Community support",
    ],
    gradient: "from-purple-500 via-indigo-600 to-blue-600",
    bgPattern: "from-purple-50 to-indigo-50",
    icon: <Trophy className="w-7 h-7" />,
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    popular: false,
    badge: "Starter",
    badgeColor: "bg-purple-500",
  },
];

export default packagesData;
